# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='champion_vector',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='defaultname', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default='defaultrank', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='recommended_champs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='top_5_champs',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
