# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161027_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='defaultname1', max_length=50),
        ),
    ]
