# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20161027_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='defaultname', max_length=50),
        ),
    ]
