# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_date_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summoner_icon',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
