# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_summoner_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='top_5_played',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
