# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_top_5_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verbose_name',
            field=models.CharField(default='defaultname', max_length=50),
        ),
    ]
